ApplicationTestBundle:
    resource: "@ApplicationTestBundle/Controller/"
    type:     annotation
    prefix:   /

ApplicationPlaceBundle:
    resource: "@ApplicationPlaceBundle/Controller/"
    type:     annotation
    prefix:   /

ApplicationEventBundle:
    resource: "@ApplicationEventBundle/Controller/"
    type:     annotation
    prefix:   /

ApplicationCityBundle:
    resource: "@ApplicationCityBundle/Controller/"
    type:     annotation
    prefix:   /

#ApplicationProjectBundle:
#    resource: "@ApplicationProjectBundle/Controller/"
#    type:     annotation
#    prefix:   /

_welcome:
    pattern:  /
    defaults: { _controller: ApplicationUserBundle:User:welcome }

ApplicationUserBundle:
    resource: "@ApplicationUserBundle/Controller/"
    type:     annotation
    prefix:   /

ApplicationAnunciosBundle:
    resource: "@ApplicationAnunciosBundle/Controller/"
    type:     annotation
    prefix:   /

ApplicationApiBundle:
    resource: "@ApplicationApiBundle/Controller/"
    type:     annotation
    prefix:   /

ApplicationPageBundle:
    resource: "@ApplicationPageBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
